# coding: utf-8

"""
    Contracts Blueprint API

    # Contracts Blueprint API  A simple API blueprint demonstrating enterprise-grade OpenAPI specifications with multi-language code generation support for Go, Python, and TypeScript.  This API provides basic authentication and user management functionality.  ## Features - JWT-based authentication - User CRUD operations - Multi-language SDK generation - Comprehensive error handling  ## Error Codes - `ERR_INTERNAL`: Internal server error - `ERR_INVALID_ARG`: Invalid argument(s) provided - `ERR_NOT_FOUND`: Resource not found - `ERR_ALREADY_EXISTS`: Resource already exists - `ERR_ACCESS_DENIED`: Access denied - `ERR_INVALID_CREDENTIALS`: Invalid authentication credentials - `ERR_VALIDATION_FAILED`: Request validation failed 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from contracts.apis.authentication_api import router as AuthenticationApiRouter
from contracts.apis.health_api import router as HealthApiRouter
from contracts.apis.users_api import router as UsersApiRouter

app = FastAPI(
    title="Contracts Blueprint API",
    description="# Contracts Blueprint API  A simple API blueprint demonstrating enterprise-grade OpenAPI specifications with multi-language code generation support for Go, Python, and TypeScript.  This API provides basic authentication and user management functionality.  ## Features - JWT-based authentication - User CRUD operations - Multi-language SDK generation - Comprehensive error handling  ## Error Codes - &#x60;ERR_INTERNAL&#x60;: Internal server error - &#x60;ERR_INVALID_ARG&#x60;: Invalid argument(s) provided - &#x60;ERR_NOT_FOUND&#x60;: Resource not found - &#x60;ERR_ALREADY_EXISTS&#x60;: Resource already exists - &#x60;ERR_ACCESS_DENIED&#x60;: Access denied - &#x60;ERR_INVALID_CREDENTIALS&#x60;: Invalid authentication credentials - &#x60;ERR_VALIDATION_FAILED&#x60;: Request validation failed ",
    version="1.0.0",
)

app.include_router(AuthenticationApiRouter)
app.include_router(HealthApiRouter)
app.include_router(UsersApiRouter)
